<?php
echo "<!doctype html>\n";
echo "<html>\n";
echo "<head>\n";
echo "<meta charset=\"utf-8\">\n";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=yes\">\n";
echo "<title>SISDX</title>\n";
echo "<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\">\n";
echo "<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.2.1.min.js\"></script>\n";
echo "<script type=\"text/javascript\" async=\"\" src=\"javascript/script.js\"></script>\n";
echo "</head>\n";
echo "<body>\n";
echo "	<div id=\"page\">\n";
echo "		<header>\n";
echo "			<div id=\"header_inner\">\n";
echo "				<div id=\"header_logo\">\n";
echo "					<img src=\"images/logo.jpg\">\n";
echo "				</div>\n";
echo "				<div id=\"header_contact\">\n";
echo "				</div>\n";
echo "			</div>\n";
echo "		</header>\n";
echo "		<main>\n";
echo "		<div class=\"slideshow\">\n";
echo "			<input type=\"radio\" name=\"slideshow\" id=\"switch1\" checked>\n";
echo "			<input type=\"radio\" name=\"slideshow\" id=\"switch2\">\n";
echo "			<input type=\"radio\" name=\"slideshow\" id=\"switch3\">\n";
echo "		<div class=\"slideContents\">\n";
echo "			<section id=\"slide1\">\n";
echo "				<a href=\"sp/sp1.html\"><img src=\"images/top01.png\" alt=\"SP1の画面へ\"></a>\n";
echo "			</section>\n";
echo "			<section id=\"slide2\">\n";
echo "				<a href=\"sp/sp2.html\"><img src=\"images/TOP_IMG02.jpg\" alt=\"SP2の画面へ\"></a>\n";
echo "			</section>\n";
echo "			<section id=\"slide3\">\n";
echo "				<a href=\"sp/sp3.html\"><img src=\"images/TOP_IMG03.jpg\" alt=\"SP3の画面へ\"></a>\n";
echo "			</section>\n";
echo "		</div>\n";
echo "		<p class=\"arrow prev\">\n";
echo "			<i class=\"ico\"></i>\n";
echo "				<label for=\"switch1\"></label>\n";
echo "				<label for=\"switch2\"></label>\n";
echo "				<label for=\"switch3\"></label>\n";
echo "		</p>\n";
echo "		<p class=\"arrow next\">\n";
echo "			<i class=\"ico\"></i>\n";
echo "				<label for=\"switch1\"></label>\n";
echo "				<label for=\"switch2\"></label>\n";
echo "				<label for=\"switch3\"></label>\n";
echo "		</p>\n";
echo "		<p class = \"underScroll\">\n";
echo "			<a href=\"#section01\"><span></span>SCROLL</a>\n";
echo "		</p>\n";
echo "		</div>\n";
echo "		<section id=\"section01\">\n";
echo "				<div class=\"scroll\">\n";
echo "					<h2>活動内容</h2>\n";
echo "				</div>\n";
echo "				<nav>\n";
echo "					<ul id=\"main_nav\">\n";
echo "						<li><a href=\"#div01\">活動実績１<br>～DXとは～</a></li>\n";
echo "						<li><a href=\"#div03\">活動実績３<br>～DXとは～</a></li>\n";
echo "						<li><a href=\"#div02\">活動実績２<br>～DXとは～</a></li>\n";
echo "					</ul>\n";
echo "				</nav>\n";
echo "				<div class=\"contents\" id=\"div01\">\n";
echo "					<div class=\"left\" id=\"photo01\">\n";
echo "					</div>\n";
echo "					<div class=\"right text\">\n";
echo "						<h4>活動実績１</h4>\n";
echo "						<p>活動内容１</p>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "				<div class=\"contents\" id=\"div02\">\n";
echo "					<div class=\"left text\">\n";
echo "						<h4>活動実績２</h4>\n";
echo "						<p>活動内容２</p>\n";
echo "					</div>\n";
echo "					<div class=\"right\" id=\"photo02\">\n";
echo "					</div>\n";
echo "				</div>\n";
echo "				<div class=\"contents\" id=\"div03\">\n";
echo "					<div class=\"left\" id=\"photo03\">\n";
echo "					</div>\n";
echo "					<div class=\"right text\">\n";
echo "						<h4>活動実績３</h4>\n";
echo "						<p>活動内容３</p>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "				<div class=\"main_contact\">\n";
echo "					<div class=\"contact_left main_contact_inner\">\n";
echo "						<div class=\"contact_left_inner\">\n";
echo "							<p>サイトマップ<br>\n";
echo "						</div>\n";
echo "					</div>\n";
echo "					<div class=\"contact_right main_contact_inner\">\n";
echo "						<a href=\"#\" class=\"contact_right_inner\">\n";
echo "							<p>画面先頭に戻る</p>\n";
echo "						</a>\n";
echo "					</div>\n";
echo "				</div>\n";
echo "			</section>\n";
echo "		</main>\n";
echo "		<footer>\n";
echo "			<p>&copy; sis</p>\n";
echo "		</footer>\n";
echo "	</div>\n";
echo "</body>\n";
echo "</html>\n";
echo "";
?>